title: |-
  The [Cloud Translation API](https://cloud.google.com/translate/docs/),
  can dynamically translate text between thousands
  of language pairs. The Cloud Translation API lets websites and programs
  integrate with the translation service programmatically. The Cloud Translation
  API is part of the larger Cloud Machine Learning API family.
